In [ ]:
# | default_exp nets/detr_3d

# Imports

In [ ]:
# | export


from functools import wraps
from typing import Literal

import torch
from einops import rearrange, repeat
from huggingface_hub import PyTorchModelHubMixin
from scipy.optimize import linear_sum_assignment
from torch import nn
from torch.nn import functional as F
from torch.nn.utils.rnn import pad_sequence

from vision_architectures.blocks.transformer import Attention1DWithMLPConfig, TransformerDecoderBlock1D
from vision_architectures.docstrings import populate_docstring
from vision_architectures.layers.embeddings import AbsolutePositionEmbeddings3D, AbsolutePositionEmbeddings3DConfig
from vision_architectures.losses.class_balanced_cross_entropy_loss import (
    ClassBalancedCrossEntropyLoss,
    ClassBalancedCrossEntropyLossConfig,
)
from vision_architectures.utils.activation_checkpointing import ActivationCheckpointing
from vision_architectures.utils.custom_base_model import CustomBaseModel, Field, model_validator
from vision_architectures.utils.rearrange import rearrange_channels

# Config

In [ ]:
# | export


class DETRDecoderConfig(Attention1DWithMLPConfig):
    num_layers: int = Field(..., description="Number of transformer decoder layers.")


class DETRBBoxMLPConfig(CustomBaseModel):
    dim: int = Field(..., description="Dimension of the input features.")
    num_classes: int = Field(..., description="Number of classes for the bounding box predictions.")
    bbox_size_activation: Literal["sigmoid", "softplus"] = Field(
        "sigmoid",
        description=(
            'Activation function for the bounding box size. "sigmoid" for normalized coordinates, "softplus" '
            "for absolute coordinates."
        ),
    )

    @model_validator(mode="after")
    def validate(self):
        super().validate()
        assert self.num_classes > 0, "Number of classes must be greater than zero. If not predicting classes, set to 1."
        return self


class DETR3DConfig(DETRDecoderConfig, DETRBBoxMLPConfig, AbsolutePositionEmbeddings3DConfig):
    num_objects: int = Field(..., description="Maximum number of objects to detect.")
    drop_prob: float = Field(0.0, description="Dropout probability for input embeddings.")
    classification_cost_fn: Literal["softmax", "log_softmax"] = Field(
        "softmax",
        description=(
            "Method used to compute classification cost in Hungarian matching. While softmax is the default (as per "
            "the paper), log_sofmtax is encouraged as the final bipartite matching loss calculation uses cross entropy "
            "loss which performs log_softmax and NLLLoss internally making log_softmax more apt."
        ),
    )
    classification_loss_fn: (
        Literal["cross_entropy", "class_balanced_cross_entropy"] | dict | ClassBalancedCrossEntropyLossConfig
    ) = Field("cross_entropy", description="Loss function for bbox classification.")

    @model_validator(mode="after")
    def validate(self):
        super().validate()

        # Create an object of ClassBalancedCrossEntropyLossConfig if applicable
        if self.classification_loss_fn == "class_balanced_cross_entropy":
            self.classification_loss_fn = ClassBalancedCrossEntropyLossConfig(num_classes=self.num_classes + 1)
        elif isinstance(self.classification_loss_fn, dict):
            self.classification_loss_fn = ClassBalancedCrossEntropyLossConfig.model_validate(
                self.classification_loss_fn
            )

        return self

# Architecture

### Decoder

In [ ]:
# | export


class DETRDecoder(nn.Module, PyTorchModelHubMixin):
    """DETR Transformer decoder."""

    @populate_docstring
    def __init__(self, config: DETRDecoderConfig = {}, checkpointing_level: int = 0, **kwargs):
        """Initialize the DETRDecoder. Activation checkpointing level 4.

        Args:
            config: {CONFIG_INSTANCE_DOC}
            checkpointing_level: {CHECKPOINTING_LEVEL_DOC}
            **kwargs: {CONFIG_KWARGS_DOC}
        """
        super().__init__()

        self.config = DETRDecoderConfig.model_validate(config | kwargs)

        self.layers = nn.ModuleList(
            [TransformerDecoderBlock1D(config, checkpointing_level) for _ in range(self.config.num_layers)]
        )

        self.checkpointing_level4 = ActivationCheckpointing(4, checkpointing_level)

    @populate_docstring
    def _forward(
        self, object_queries: torch.Tensor, embeddings: torch.Tensor, return_intermediates: bool = False
    ) -> torch.Tensor | tuple[torch.Tensor, list[torch.Tensor]]:
        """Forward pass of the DETR3D decoder.

        Args:
            object_queries: Tokens that represent object queries. {INPUT_1D_DOC}
            embeddings: Actual embeddings of the input. {INPUT_1D_DOC}
            return_intermediates: If True, also returns the outputs of all layers. Defaults to False.

        Returns:
            If return_intermediates is True, returns the final object embeddings and a list of outputs from all layers.
            Otherwise, returns only the final object embeddings.
        """
        # object_queries: (b, num_possible_objects, dim)
        # embeddings: (b, num_embed_tokens, dim)

        object_embeddings = object_queries

        layer_outputs = []
        for layer in self.layers:
            object_embeddings = layer(object_embeddings, embeddings)
            layer_outputs.append(object_embeddings)

        if return_intermediates:
            return object_embeddings, layer_outputs
        return object_embeddings

    @wraps(_forward)
    def forward(self, *args, **kwargs):
        return self.checkpointing_level4(self._forward, *args, **kwargs)

In [ ]:
test_config = {
    "attn_drop_prob": 0.2,
    "dim": 54,
    "drop_prob": 0.2,
    "embed_spacing_info": False,
    "in_channels": 1,
    "mlp_ratio": 2,
    "layer_norm_eps": 1e-6,
    "learnable_absolute_position_embeddings": False,
    "mlp_drop_prob": 0.2,
    "num_heads": 6,
    "patch_size": (8, 16, 16),
    "proj_drop_prob": 0.2,
    "num_layers": 4,
}

test = DETRDecoder(test_config)
display(test)
o = test(
    torch.randn(2, 10, 54),
    torch.randn(2, 64, 54),
    True,
)
display((o[0].shape, [x.shape for x in o[1]]))


DETRDecoder(
  (layers): ModuleList(
    (0-3): 4 x TransformerDecoderBlock1D(
      (attn1): Attention1D(
        (W_q): Linear(in_features=54, out_features=54, bias=True)
        (W_k): Linear(in_features=54, out_features=54, bias=True)
        (W_v): Linear(in_features=54, out_features=54, bias=True)
        (proj): Linear(in_features=54, out_features=54, bias=True)
        (proj_drop): Dropout(p=0.2, inplace=False)
        (checkpointing_level1): ActivationCheckpointing(enabled=False)
        (checkpointing_level2): ActivationCheckpointing(enabled=False)
      )
      (layernorm1): LayerNorm((54,), eps=1e-06, elementwise_affine=True)
      (attn2): Attention1D(
        (W_q): Linear(in_features=54, out_features=54, bias=True)
        (W_k): Linear(in_features=54, out_features=54, bias=True)
        (W_v): Linear(in_features=54, out_features=54, bias=True)
        (proj): Linear(in_features=54, out_features=54, bias=True)
        (proj_drop): Dropout(p=0.2, inplace=False)
        (


(
    torch.Size([2, 10, 54]),
    [
        torch.Size([2, 10, 54]),
        torch.Size([2, 10, 54]),
        torch.Size([2, 10, 54]),
        torch.Size([2, 10, 54])
    ]
)

In [ ]:
# | export


class DETRBBoxMLP(nn.Module):
    """DETR Bounding Box MLP. This module predicts bounding boxes and class scores from object query embeddings."""

    @populate_docstring
    def __init__(self, config: DETRBBoxMLPConfig = {}, **kwargs):
        """Initialize the DETRBBoxMLP.

        Args:
            config: {CONFIG_INSTANCE_DOC}
            **kwargs: {CONFIG_KWARGS_DOC}
        """
        super().__init__()

        self.config = DETRBBoxMLPConfig.model_validate(config | kwargs)

        # Keeping bbox and classification heads separate so that bias-init/clipping/freezing can be done if needed
        self.bbox_head = nn.Linear(self.config.dim, 6)
        self.class_head = nn.Linear(self.config.dim, 1 + self.config.num_classes)

    @populate_docstring
    def forward(
        self,
        object_embeddings: torch.Tensor,
    ) -> torch.Tensor:
        """Forward pass of the DETRBBoxMLP.

        Args:
            object_embeddings: Object embeddings from the DETR decoder. {INPUT_1D_DOC}

        Returns:
            A tensor of shape (b, num_possible_objects, 1 objectness class + 6 bounding box parameters + num_classes)
            containing the predicted bounding boxes and class scores. {BOUNDING_BOXES_FORMAT_DOC}
        """
        # object_embeddings: (b, num_possible_objects, dim)

        bbox_parameters: torch.Tensor = self.bbox_head(object_embeddings)
        class_logits: torch.Tensor = self.class_head(object_embeddings)
        # (b, num_possible_objects, 6 + 1 + num_classes)

        # Bound the bounding box parameters
        centers, sizes = bbox_parameters[:, :, :3], bbox_parameters[:, :, 3:6]
        centers = centers.sigmoid()  # center coordinates should be in the bbox
        if self.config.bbox_size_activation == "sigmoid":
            sizes = sizes.sigmoid()  # sizes should be between 0 and 1
        elif self.config.bbox_size_activation == "softplus":
            sizes = F.softplus(sizes)  # sizes should be positive but unbounded
        bboxes = torch.cat([centers, sizes, class_logits], dim=-1)

        return bboxes

In [ ]:
test_config = {
    "dim": 54,
    "num_classes": 10,
}

test = DETRBBoxMLP(test_config)
display(test)
o = test(
    torch.randn(2, 10, 54),
)
display((o[0].shape), o[0][0])


DETRBBoxMLP(
  (bbox_head): Linear(in_features=54, out_features=6, bias=True)
  (class_head): Linear(in_features=54, out_features=11, bias=True)
)

torch.Size([10, 17])


tensor([ 0.3917,  0.5846,  0.2497,  0.4194,  0.4995,  0.6928,  0.1971, -0.3480,
         0.8096,  0.8929, -0.2808,  0.0617, -0.6956, -0.3701, -0.4366,  0.3426,
        -0.0956], grad_fn=<SelectBackward0>)

# Helper functions

In [ ]:
# | export


def bbox_zyxdhw_to_z1z2y1y2x1x2(bboxes: torch.Tensor) -> torch.Tensor:
    """Convert bboxes from center format (z, y, x, d, h, w) to corner format (z1, z2, y1, y2, x1, x2)

    Args:
        bboxes: Bounding boxes of shape (N, 6) in center format (z, y, x, d, h, w)

    Returns:
        Bounding boxes of shape (N, 6) in corner format (z1, z2, y1, y2, x1, x2)
    """
    centers = bboxes[:, :3]
    sizes = bboxes[:, 3:] / 2
    min_coords = centers - sizes
    max_coords = centers + sizes
    return torch.cat([min_coords, max_coords], dim=1)  # shape (N, 6)

# Models

In [ ]:
# | export


class DETR3D(nn.Module, PyTorchModelHubMixin):
    """DETR 3D model. Also implements bipartite matching loss which is essential for DETR training."""

    @populate_docstring
    def __init__(self, config: DETR3DConfig = {}, checkpointing_level: int = 0, **kwargs):
        """Initialize the DETR3D. Activation checkpointing level 4.

        Args:
            config: {CONFIG_INSTANCE_DOC}
            checkpointing_level: {CHECKPOINTING_LEVEL_DOC}
            **kwargs: {CONFIG_KWARGS_DOC}
        """
        super().__init__()

        self.config = DETR3DConfig.model_validate(config | kwargs)

        self.position_embeddings = AbsolutePositionEmbeddings3D(config)
        self.pos_drop = nn.Dropout(self.config.drop_prob)
        self.num_possible_objects = self.config.num_objects
        self.object_queries = nn.Parameter(torch.randn(1, self.num_possible_objects, self.config.dim) * 0.01)
        self.decoder = DETRDecoder(config, checkpointing_level)
        self.bbox_mlp = DETRBBoxMLP(config)

        self.class_balanced_cross_entropy_loss = None
        if isinstance(self.config.classification_loss_fn, ClassBalancedCrossEntropyLossConfig):
            self.class_balanced_cross_entropy_loss = ClassBalancedCrossEntropyLoss(
                config=self.config.classification_loss_fn
            )

        self.checkpointing_level4 = ActivationCheckpointing(4, checkpointing_level)

    @populate_docstring
    def _forward(
        self,
        embeddings: torch.Tensor,
        spacings: torch.Tensor | None = None,
        channels_first: bool = True,
        return_intermediates: bool = False,
        process_intermediates: bool = True,
    ) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor, list[torch.Tensor]]:
        """Forward pass of the DETR3D.

        Args:
            embeddings: Encoded input features. {INPUT_3D_DOC}
            spacings: {SPACINGS_DOC}
            channels_first: {CHANNELS_FIRST_DOC}
            return_intermediates: If True, also returns the outputs of all layers. Defaults to False.
            process_intermediates: If True, passes the layer outputs through the bbox_mlp too. Requires
                `return_intermediates` to be True too.

        Returns:
            A tuple containing bounding boxes, object embeddings, and layer outputs if return_intermediates is True.
            Else, returns only the bounding boxes. {BOUNDING_BOXES_FORMAT_DOC}
        """
        # embeddings: (b, [dim], num_tokens_z, num_tokens_y, num_tokens_x, [dim])
        # spacings: (b, 3)

        embeddings = rearrange_channels(embeddings, channels_first, True)
        # (b, dim, num_tokens_z, num_tokens_y, num_tokens_x)

        embeddings = self.position_embeddings(embeddings, spacings=spacings)
        embeddings = self.pos_drop(embeddings)
        # (b, dim, num_tokens_z, num_tokens_y, num_tokens_x)

        embeddings = rearrange(embeddings, "b d z y x -> b (z y x) d")
        # (b, num_embed_tokens, dim)

        object_queries = repeat(self.object_queries, "1 n d -> b n d", b=embeddings.shape[0])
        # (b, num_possible_objects, dim)

        object_embeddings, layer_outputs = self.decoder(object_queries, embeddings, return_intermediates=True)
        # object_embeddings: (b, num_possible_objects, dim)
        # layer_outputs: list of (b, num_possible_objects, dim)

        bboxes = self.bbox_mlp(object_embeddings)
        # (b, num_possible_objects, 6 + 1 + num_classes)

        if return_intermediates:
            if process_intermediates:
                for i in range(len(layer_outputs)):
                    layer_outputs[i] = self.bbox_mlp(layer_outputs[i])
            return bboxes, object_embeddings, layer_outputs

        return bboxes

    @wraps(_forward)
    def forward(self, *args, **kwargs):
        return self.checkpointing_level4(self._forward, *args, **kwargs)

    def bipartite_matching_loss(
        self,
        pred: torch.Tensor,
        target: torch.Tensor | list[torch.Tensor],
        intermediate_preds: list[torch.Tensor] | None = None,
        classification_cost_weight: float = 1.0,
        bbox_l1_cost_weight: float = 1.0,
        bbox_giou_cost_weight: float = 1.0,
        matched_indices: tuple[list[int], list[int]] | None = None,
        update_class_prevalences: bool = True,
        reduction: str = "mean",
        return_matching: bool = False,
        return_loss_components: bool = False,
    ) -> (
        torch.Tensor  # just loss
        | list[torch.Tensor]  # main loss plus auxiliary losses
        | tuple[torch.Tensor, tuple]  # loss with matching
        | tuple[list[torch.Tensor], tuple]  # main+auxiliary losses with matching
        | tuple[torch.Tensor, dict[str, torch.Tensor]]  # loss with loss components
        | tuple[list[torch.Tensor], list[dict[str, torch.Tensor]]]  # main+auxiliary losses with loss components
        | tuple[torch.Tensor, tuple, dict[str, torch.Tensor]]  # loss, matching, loss components
        | tuple[list[torch.Tensor], tuple, list[dict[str, torch.Tensor]]]  # all losses, matching, all loss components
    ):
        """Bipartite matching loss for DETR. The classes are expected to optimize for a multi-class classification
        problem. Expects raw logits in class predictions, not probabilities. Use ``logits_to_scores_fn=None`` in the
        ``forward`` function to avoid applying any transformation.

        Args:
            pred: Predicted bounding boxes and class scores. It should be of shape
                `(B, num_objects, 6 + 1 + num_classes)`. Number of objects and number of classes will be inferred from
                here.
            target: Target bounding boxes and class scores. If provided as a list, each element should be a tensor for
                the corresponding batch element in ``pred`` and therefore should have a length of `B`. Each tensor
                should have less than or equal to the number of objects in `pred`. The number of classes can either be
                the exact same as in `pred`, or it should be 1 argmax (one-cold) decoding.
            intermediate_preds: A list of any intermediate decoder outputs to use for auxiliary losses. If provided,
                returned loss values become a list instead of single values. The matching used is the one used for the
                final prediction i.e. `pred`.
            classification_cost_weight: Weight for the classification cost in hungarian matching. Only used when
                matched_indices is None.
            bbox_l1_cost_weight: Weight for the bounding box L1 loss cost in hungarian matching. Only used when
                matched_indices is None.
            bbox_giou_cost_weight: Weight for the bounding box IoU cost in hungarian matching. Only used when
                matched_indices is None.
            matched_indices: Hungarian matching is done only if this is None, else this is used to match pred and target
                boxes. Useful when calculating auxiliary losses with intermediate layers of DETR3D.
            update_class_prevalences: Whether or not to update class prevalences in the class balanced cross entropy
                loss. Useful when calculating auxiliary losses with intermediate layers of DETR3D.
            reduction: Specifies the reduction to apply to the output.
            return_matching: Whether or not to return the matched indices from the bipartite matching.
            return_loss_components: Whether or not to return the individual loss components.

        Returns:
            The first element is always the main loss that has been calculated. If no `intermediate_preds` were
            provided, a tensor containing the bipartite matching loss with the shape depending on the `reduction`
            argument is present, else it is a list of the same for all preds provided with the first one being the main
            pred.

            If `return_matching` is True, also returns a list of tuples containing matched indices for predictions and
            targets. Each tuple is of the form `(pred_indices, target_indices)`, where `pred_indices` and
            `target_indices` are lists of indices for the matched predictions and targets, respectively.

            If `return_loss_components` is True, also returns a dict of each loss component reduced based on
            `reduction`. If `intermediate_preds` were also provided, it is a list of the same.
        """
        B = pred.shape[0]

        # Convert target to a list of tensors if not already
        if isinstance(target, torch.Tensor):
            target = list(target)

        # argmax encode the class labels if they are not already
        for i in range(len(target)):
            if target[i].shape[-1] > 7:  # 6 bbox + 1 class
                target[i] = torch.cat([target[i][:, :6], target[i][:, 6:].argmax(-1, keepdims=True)], dim=-1)

        # Perform hungarian matching
        if matched_indices is None:
            matched_indices = self.hungarian_matching(
                pred, target, classification_cost_weight, bbox_l1_cost_weight, bbox_giou_cost_weight
            )

        # Update class prevalences in class balanced cross entropy loss
        if update_class_prevalences:
            self._update_class_prevalences(target)

        # Get a combined list of all preds
        all_preds = [pred]
        if intermediate_preds is not None:
            all_preds += intermediate_preds

        # Calculate losses for all preds
        loss = []
        loss_components = []
        for pred in all_preds:  # pred is overwritten here
            batch_loss_components = {
                "classification_loss": [],
                "bbox_l1_loss": [],
                "bbox_giou_loss": [],
                "total_loss": [],
            }
            for i in range(B):
                batch_losses = {}

                pred_indices, target_indices = matched_indices[i]

                # Classification loss for ALL predictions
                all_class_labels = torch.zeros_like(pred[i][:, 6], dtype=torch.long)
                all_class_labels[pred_indices] = target[i][target_indices, 6].long()
                all_pred_classes = pred[i][..., 6:]
                if self.class_balanced_cross_entropy_loss is None:
                    batch_losses["classification_loss"] = F.cross_entropy(all_pred_classes, all_class_labels)
                else:
                    batch_losses["classification_loss"] = self.class_balanced_cross_entropy_loss(
                        all_pred_classes, all_class_labels, update_class_prevalences=False
                    )

                # Calculate all other losses only if prediction and target have objects
                if pred_indices != [] and target_indices != []:
                    matched_pred = pred[i][pred_indices]
                    matched_target = target[i][target_indices]

                    pred_bboxes = matched_pred[:, :6].clone()
                    target_bboxes = matched_target[:, :6].clone()

                    # Compute losses for matched pairs
                    # BBox L1 loss
                    batch_losses["bbox_l1_loss"] = F.l1_loss(pred_bboxes, target_bboxes)

                    # For IOU calculation, it does not matter if bboxes are in actual pixel lengths or normalized based on
                    # image size, metric value will be the same.

                    # BBox IOU loss
                    batch_losses["bbox_giou_loss"] = 1 - DETR3D.generalized_bbox_iou(pred_bboxes, target_bboxes).mean()

                # Total loss for this batch element
                total_loss = (
                    classification_cost_weight * batch_losses.get("classification_loss", 0.0)
                    + bbox_l1_cost_weight * batch_losses.get("bbox_l1_loss", 0.0)
                    + bbox_giou_cost_weight * batch_losses.get("bbox_giou_loss", 0.0)
                )

                # Add to losses
                batch_loss_components["classification_loss"].append(
                    batch_losses.get("classification_loss", torch.tensor(torch.nan, device=pred.device)),
                )
                batch_loss_components["bbox_l1_loss"].append(
                    batch_losses.get("bbox_l1_loss", torch.tensor(torch.nan, device=pred.device)),
                )
                batch_loss_components["bbox_giou_loss"].append(
                    batch_losses.get("bbox_giou_loss", torch.tensor(torch.nan, device=pred.device)),
                )
                batch_loss_components["total_loss"].append(total_loss)

            # Stack batch losses and apply reduction
            for key in batch_loss_components:
                batch_loss_component = torch.stack(batch_loss_components[key])

                if reduction == "mean":
                    batch_loss_component = batch_loss_component.nanmean()
                elif reduction == "sum":
                    batch_loss_component = batch_loss_component.nansum()
                elif reduction == "none" or reduction is None:
                    pass
                else:
                    raise ValueError(f"Invalid reduction mode: {reduction}")

                batch_loss_components[key] = batch_loss_component

            loss.append(batch_loss_components.pop("total_loss"))
            loss_components.append(batch_loss_components)

        # Finalize return value
        if len(loss) == 1:
            loss = loss[0]
            loss_components = loss_components[0]

        return_value = [loss]
        if return_matching:
            return_value.append(matched_indices)
        if return_loss_components:
            return_value.append(loss_components)

        if len(return_value) == 1:
            return_value = return_value[0]
        else:
            return_value = tuple(return_value)

        return return_value

    @torch.no_grad()
    def hungarian_matching(
        self,
        pred: torch.Tensor,
        target: list[torch.Tensor],
        classification_cost_weight: float = 1.0,
        bbox_l1_cost_weight: float = 1.0,
        bbox_giou_cost_weight: float = 1.0,
    ) -> list[tuple[list[int], list[int]]]:
        """Hungarian matching between predictions and targets.

        Args:
            pred: Predicted bounding boxes and class scores. It should be of shape
                `(B, num_objects, 6 + 1 + num_classes)`. Number of objects and number of classes will be inferred from
                here.
            target: Target bounding boxes and class scores. This is expected in argmax encoding or one-hot encoding.
            classification_cost_weight: Weight for the classification cost.
            bbox_l1_cost_weight: Weight for the bounding box L1 loss cost.
            bbox_giou_cost_weight: Weight for the bounding box IoU cost.

        Returns:
            A list of tuples containing matched indices for predictions and targets. Each tuple is of the form
            `(pred_indices, target_indices)`, where `pred_indices` and `target_indices` are lists of indices for the
            matched predictions and targets, respectively.
        """
        B = pred.shape[0]

        matched_indices = []
        for i in range(B):
            pred_bboxes = pred[i, :, :6]  # (num_objects, 6)
            target_bboxes = target[i][:, :6]  # (<=num_objects, 6)

            # If either prediction or target has no objects, skip matching
            if pred_bboxes.shape[0] == 0 or target_bboxes.shape[0] == 0:
                matched_indices.append(([], []))
                continue

            pred_class_logits = pred[i, :, 6:]  # (num_objects, num_classes)
            target_class_labels = target[i][:, 6].long()  # (<=num_objects,) this is in argmax encoding

            # ----- Cost matrix calculation -----

            # Classification cost
            if self.config.classification_cost_fn == "softmax":
                pred_class_probabilities = F.softmax(pred_class_logits, dim=-1)
            elif self.config.classification_cost_fn == "log_softmax":
                pred_class_probabilities = F.log_softmax(pred_class_logits, dim=-1)
            # (num_objects, num_classes)

            classification_cost = -pred_class_probabilities[:, target_class_labels]
            # (num_objects, <=num_objects)

            # L1 loss for bounding boxes
            bbox_l1_cost = torch.cdist(pred_bboxes, target_bboxes, p=1)
            # (num_objects, <=num_objects)

            # IOU cost for bounding boxes
            bbox_giou_cost = 1 - DETR3D.generalized_pairwise_bbox_iou(pred_bboxes, target_bboxes)
            # (num_objects, <=num_objects)

            # Total cost matrix
            cost_matrix = (
                classification_cost_weight * classification_cost
                + bbox_l1_cost_weight * bbox_l1_cost
                + bbox_giou_cost_weight * bbox_giou_cost
            )
            # (num_objects, <=num_objects)

            # Hungarian matching
            pred_indices_element, target_indices_element = linear_sum_assignment(cost_matrix.detach().cpu().numpy())

            matched_indices.append((list(pred_indices_element), list(target_indices_element)))

        return matched_indices

    @staticmethod
    @populate_docstring
    def bbox_iou(
        pred_bboxes: torch.Tensor,
        target_bboxes: torch.Tensor,
    ) -> torch.Tensor:
        """Compute the IoU between two matched sets of bounding boxes.

        Args:
            pred_bboxes: Predicted bounding boxes of shape `(num_boxes, 6)`. {BOUNDING_BOXES_FORMAT_DOC}
            target_bboxes: Target bounding boxes of shape `(num_boxes, 6)`. {BOUNDING_BOXES_FORMAT_DOC}

        Returns:
            A tensor containing the IoU.
        """
        pred_corners = bbox_zyxdhw_to_z1z2y1y2x1x2(pred_bboxes)
        target_corners = bbox_zyxdhw_to_z1z2y1y2x1x2(target_bboxes)

        # Intersection corners
        max_min = torch.max(pred_corners[:, :3], target_corners[:, :3])
        min_max = torch.min(pred_corners[:, 3:], target_corners[:, 3:])
        inter_dims = (min_max - max_min).clamp(min=0)
        inter_vol = inter_dims.prod(dim=1)

        # Volumes
        pred_dims = pred_corners[:, 3:] - pred_corners[:, :3]
        target_dims = target_corners[:, 3:] - target_corners[:, :3]
        pred_vol = pred_dims.prod(dim=1)
        target_vol = target_dims.prod(dim=1)
        union_vol = pred_vol + target_vol - inter_vol

        # IOU
        iou = inter_vol / union_vol.clamp(min=1e-7)

        return iou

    @staticmethod
    @populate_docstring
    def generalized_bbox_iou(
        pred_bboxes: torch.Tensor,
        target_bboxes: torch.Tensor,
    ) -> torch.Tensor:
        """Compute the IoU loss between two matched sets of bounding boxes.

        Args:
            pred_bboxes: Predicted bounding boxes of shape `(num_boxes, 6)`. {BOUNDING_BOXES_FORMAT_DOC}
            target_bboxes: Target bounding boxes of shape `(num_boxes, 6)`. {BOUNDING_BOXES_FORMAT_DOC}

        Returns:
            A tensor containing the IoU loss.
        """
        pred_corners = bbox_zyxdhw_to_z1z2y1y2x1x2(pred_bboxes)
        target_corners = bbox_zyxdhw_to_z1z2y1y2x1x2(target_bboxes)

        # Intersection corners
        max_min = torch.max(pred_corners[:, :3], target_corners[:, :3])
        min_max = torch.min(pred_corners[:, 3:], target_corners[:, 3:])
        inter_dims = (min_max - max_min).clamp(min=0)
        inter_vol = inter_dims.prod(dim=1)

        # Volumes
        pred_dims = pred_corners[:, 3:] - pred_corners[:, :3]
        target_dims = target_corners[:, 3:] - target_corners[:, :3]
        pred_vol = pred_dims.prod(dim=1)
        target_vol = target_dims.prod(dim=1)
        union_vol = pred_vol + target_vol - inter_vol

        # IOU
        iou = inter_vol / union_vol.clamp(min=1e-7)
        # Enclosing box corners
        enc_min = torch.min(pred_corners[:, :3], target_corners[:, :3])
        enc_max = torch.max(pred_corners[:, 3:], target_corners[:, 3:])
        enc_dims = (enc_max - enc_min).clamp(min=0)
        enc_vol = enc_dims.prod(dim=1)

        gious = iou - (enc_vol - union_vol) / enc_vol.clamp(min=1e-7)

        return gious

    @staticmethod
    @populate_docstring
    def generalized_pairwise_bbox_iou(
        pred_bboxes: torch.Tensor,
        target_bboxes: torch.Tensor,
    ) -> torch.Tensor:
        """Compute the IoU loss between all combinations of predicted and target bounding boxes.

        Args:
            pred_bboxes: Predicted bounding boxes of shape `(num_objects, 6)`. {BOUNDING_BOXES_FORMAT_DOC}
            target_bboxes: Target bounding boxes of shape `(<=num_objects, 6)`. {BOUNDING_BOXES_FORMAT_DOC}

        Returns:
            A tensor containing the IoU losses of all combinations.
        """
        # Compute pairwise IoU
        gious = []
        for i in range(pred_bboxes.shape[0]):
            row_gious = []
            for j in range(target_bboxes.shape[0]):
                row_gious.append(DETR3D.generalized_bbox_iou(pred_bboxes[i : i + 1], target_bboxes[j : j + 1]).mean())

            gious.append(torch.stack(row_gious))

        return torch.stack(gious)

    def _update_class_prevalences(self, target: list[torch.Tensor]):
        """Update the class prevalences based on the classes present in the ground truth

        Args:
            target: A list of ground truth tensors, each of shape (num_objects, 7) where the last dimension contains the
                bounding box class.
        """
        if self.class_balanced_cross_entropy_loss is not None:
            # Note that target classes will not be in order here. But since counts are all that matters, this doesn't
            # affect the results
            target_classes = pad_sequence(target, batch_first=True)[..., -1].long()
            if target_classes.shape[-1] > self.config.num_objects:
                # If there are more than self.config.num_objects targets, only the first self.config.num_objects will be
                # considered
                target_classes = target_classes[..., : self.config.num_objects]
            elif target_classes.shape[-1] < self.config.num_objects:
                # If there are less than self.config.num_objects targets, pad with background class
                target_classes = F.pad(target_classes, (0, self.config.num_objects - target_classes.shape[-1]), value=0)
            self.class_balanced_cross_entropy_loss.update_class_prevalences(target_classes)

In [ ]:
test_config = {
    "patch_size": (8, 16, 16),
    "in_channels": 1,
    "dim": 54,
    "num_heads": 6,
    "mlp_ratio": 2,
    "layer_norm_eps": 1e-6,
    "attn_drop_prob": 0.2,
    "proj_drop_prob": 0.2,
    "mlp_drop_prob": 0.2,
    "learnable_absolute_position_embeddings": True,
    "embed_spacing_info": False,
    "image_size": (32, 512, 512),
    "num_objects": 10,
    "num_classes": 5,
    "num_layers": 4,
}

test = DETR3D(test_config)
display(test)
o = test(
    torch.randn(2, 1, 4, 32, 32),
    torch.randn(2, 3),
    return_intermediates=True,
)
display((o[0].shape, o[1].shape, [x.shape for x in o[2]]))

for gt_bboxes in [
    [
        torch.cat([torch.rand(10, 6), torch.randint(0, 6, (10, 1))], dim=-1),
        torch.cat([torch.rand(2, 6), torch.randint(0, 6, (2, 1))], dim=-1),
    ],  # Regular testing
    [
        torch.rand(10, 12),
        torch.rand(2, 12),
    ],  # Requiring argmax encoding
    [
        torch.tensor([]).reshape(0, 12),
        torch.tensor([]).reshape(0, 7),
    ],  # No ground truth boxes, classification loss should still be calculated
]:
    display(test.bipartite_matching_loss(o[0], gt_bboxes, reduction="none", return_loss_components=True))


DETR3D(
  (position_embeddings): AbsolutePositionEmbeddings3D()
  (pos_drop): Dropout(p=0.0, inplace=False)
  (decoder): DETRDecoder(
    (layers): ModuleList(
      (0-3): 4 x TransformerDecoderBlock1D(
        (attn1): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, out_features=54, bias=True)
          (proj): Linear(in_features=54, out_features=54, bias=True)
          (proj_drop): Dropout(p=0.2, inplace=False)
          (checkpointing_level1): ActivationCheckpointing(enabled=False)
          (checkpointing_level2): ActivationCheckpointing(enabled=False)
        )
        (layernorm1): LayerNorm((54,), eps=1e-06, elementwise_affine=True)
        (attn2): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, ou


(
    torch.Size([2, 10, 12]),
    torch.Size([2, 10, 54]),
    [
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12])
    ]
)


(
    tensor([4.6000, 2.9489], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([2.7217, 1.6751], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([0.2963, 0.2389], grad_fn=<StackBackward0>),
        'bbox_giou_loss': tensor([1.5820, 1.0349], grad_fn=<StackBackward0>)
    }
)


(
    tensor([3.9040, 3.4109], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([1.9519, 1.9546], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([0.2921, 0.2405], grad_fn=<StackBackward0>),
        'bbox_giou_loss': tensor([1.6601, 1.2157], grad_fn=<StackBackward0>)
    }
)


(
    tensor([2.1474, 1.8935], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([2.1474, 1.8935], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([nan, nan]),
        'bbox_giou_loss': tensor([nan, nan])
    }
)

In [ ]:
test_config = {
    "patch_size": (8, 16, 16),
    "in_channels": 1,
    "dim": 54,
    "num_heads": 6,
    "mlp_ratio": 2,
    "layer_norm_eps": 1e-6,
    "attn_drop_prob": 0.2,
    "proj_drop_prob": 0.2,
    "mlp_drop_prob": 0.2,
    "learnable_absolute_position_embeddings": True,
    "embed_spacing_info": False,
    "image_size": (32, 512, 512),
    "num_objects": 10,
    "num_classes": 5,
    "num_layers": 4,
    "classification_loss_fn": "class_balanced_cross_entropy",
}

test = DETR3D(test_config)
display(test)
o = test(
    torch.randn(2, 1, 4, 32, 32),
    torch.randn(2, 3),
    return_intermediates=True,
)
display((o[0].shape, o[1].shape, [x.shape for x in o[2]]))

for gt_bboxes in [
    [
        torch.tensor([]).reshape(0, 12),
        torch.tensor([]).reshape(0, 7),
    ],  # No ground truth boxes, classification loss should still be calculated
    [
        torch.cat([torch.rand(10, 6), torch.randint(0, 6, (10, 1))], dim=-1),
        torch.cat([torch.rand(2, 6), torch.randint(0, 6, (2, 1))], dim=-1),
    ],  # Regular testing
    [
        torch.rand(10, 12),
        torch.rand(2, 12),
    ],  # Requiring argmax encoding
]:
    display(
        test.bipartite_matching_loss(o[0], gt_bboxes, reduction="none", return_loss_components=True),
        test.class_balanced_cross_entropy_loss.get_class_weights(),
    )


DETR3D(
  (position_embeddings): AbsolutePositionEmbeddings3D()
  (pos_drop): Dropout(p=0.0, inplace=False)
  (decoder): DETRDecoder(
    (layers): ModuleList(
      (0-3): 4 x TransformerDecoderBlock1D(
        (attn1): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, out_features=54, bias=True)
          (proj): Linear(in_features=54, out_features=54, bias=True)
          (proj_drop): Dropout(p=0.2, inplace=False)
          (checkpointing_level1): ActivationCheckpointing(enabled=False)
          (checkpointing_level2): ActivationCheckpointing(enabled=False)
        )
        (layernorm1): LayerNorm((54,), eps=1e-06, elementwise_affine=True)
        (attn2): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, ou


(
    torch.Size([2, 10, 12]),
    torch.Size([2, 10, 54]),
    [
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12])
    ]
)

/home/users/arjun.agarwal/projects/vision_architectures/vision_architectures/losses/class_balanced_cross_entropy_loss.py:152: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /pytorch/aten/src/ATen/native/ReduceOps.cpp:1831.)
  mu, std = weights.nanmean(), weights[~weights.isnan()].std()



(
    tensor([2.9890, 3.4998], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([2.9890, 3.4998], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([nan, nan]),
        'bbox_giou_loss': tensor([nan, nan])
    }
)

tensor([1., 1., 1., 1., 1., 1.])


(
    tensor([4.4833, 4.3253], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([2.8460, 2.5242], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([0.2587, 0.3132], grad_fn=<StackBackward0>),
        'bbox_giou_loss': tensor([1.3786, 1.4879], grad_fn=<StackBackward0>)
    }
)

tensor([0.0954, 1.8986, 1.8986, 0.4746, 0.6329, 1.0000])


(
    tensor([4.9778, 5.5608], grad_fn=<StackBackward0>),
    {
        'classification_loss': tensor([3.2387, 3.8991], grad_fn=<StackBackward0>),
        'bbox_l1_loss': tensor([0.2993, 0.2937], grad_fn=<StackBackward0>),
        'bbox_giou_loss': tensor([1.4398, 1.3680], grad_fn=<StackBackward0>)
    }
)

tensor([0.0968, 1.8988, 1.8802, 0.4807, 0.6436, 1.0000])

In [ ]:
test_config = {
    "patch_size": (8, 16, 16),
    "in_channels": 1,
    "dim": 54,
    "num_heads": 6,
    "mlp_ratio": 2,
    "layer_norm_eps": 1e-6,
    "attn_drop_prob": 0.2,
    "proj_drop_prob": 0.2,
    "mlp_drop_prob": 0.2,
    "learnable_absolute_position_embeddings": True,
    "embed_spacing_info": False,
    "image_size": (32, 512, 512),
    "num_objects": 10,
    "num_classes": 5,
    "num_layers": 4,
    "classification_loss_fn": "class_balanced_cross_entropy",
}

test = DETR3D(test_config)
display(test)
o = test(
    torch.randn(2, 1, 4, 32, 32),
    torch.randn(2, 3),
    return_intermediates=True,
)
display((o[0].shape, o[1].shape, [x.shape for x in o[2]]))

gt_bboxes = [
    torch.cat([torch.rand(10, 6), torch.randint(0, 6, (10, 1))], dim=-1),
    torch.cat([torch.rand(2, 6), torch.randint(0, 6, (2, 1))], dim=-1),
]
display(test.bipartite_matching_loss(o[0], gt_bboxes, o[2][-2:], reduction="none", return_loss_components=True))


DETR3D(
  (position_embeddings): AbsolutePositionEmbeddings3D()
  (pos_drop): Dropout(p=0.0, inplace=False)
  (decoder): DETRDecoder(
    (layers): ModuleList(
      (0-3): 4 x TransformerDecoderBlock1D(
        (attn1): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, out_features=54, bias=True)
          (proj): Linear(in_features=54, out_features=54, bias=True)
          (proj_drop): Dropout(p=0.2, inplace=False)
          (checkpointing_level1): ActivationCheckpointing(enabled=False)
          (checkpointing_level2): ActivationCheckpointing(enabled=False)
        )
        (layernorm1): LayerNorm((54,), eps=1e-06, elementwise_affine=True)
        (attn2): Attention1D(
          (W_q): Linear(in_features=54, out_features=54, bias=True)
          (W_k): Linear(in_features=54, out_features=54, bias=True)
          (W_v): Linear(in_features=54, ou


(
    torch.Size([2, 10, 12]),
    torch.Size([2, 10, 54]),
    [
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12]),
        torch.Size([2, 10, 12])
    ]
)


(
    [
        tensor([5.0699, 3.5974], grad_fn=<StackBackward0>),
        tensor([4.3932, 3.4228], grad_fn=<StackBackward0>),
        tensor([5.0699, 3.5974], grad_fn=<StackBackward0>)
    ],
    [
        {
            'classification_loss': tensor([3.1020, 2.0411], grad_fn=<StackBackward0>),
            'bbox_l1_loss': tensor([0.2642, 0.1645], grad_fn=<StackBackward0>),
            'bbox_giou_loss': tensor([1.7037, 1.3918], grad_fn=<StackBackward0>)
        },
        {
            'classification_loss': tensor([2.5019, 1.4951], grad_fn=<StackBackward0>),
            'bbox_l1_loss': tensor([0.2550, 0.2248], grad_fn=<StackBackward0>),
            'bbox_giou_loss': tensor([1.6363, 1.7029], grad_fn=<StackBackward0>)
        },
        {
            'classification_loss': tensor([3.1020, 2.0411], grad_fn=<StackBackward0>),
            'bbox_l1_loss': tensor([0.2642, 0.1645], grad_fn=<StackBackward0>),
            'bbox_giou_loss': tensor([1.7037, 1.3918], grad_fn=<StackBackward0>)
   

# nbdev

In [ ]:
!nbdev_export